j2ga:
  github:
    url: api.github.com
    username: your_github_username
    email: your_email@gmail.com
    token: your_github_token
  jenkins2githubWorkflowsMap:
    JenkinsGradleSharedLibrary: java-gradle-workflow
    JenkinsMavenSharedLibrary: java-maven-workflow