j2ga:
  github:
    url: api.github.com
    username: aditya-mittal
    email: aditya.mittal@equalexperts.com
    token: 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
  jenkins2githubWorkflowsMap:
    JenkinsGradleSharedLibrary: java-gradle-workflow
    JenkinsMavenSharedLibrary: java-maven-workflow